[project]
name = "task1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Youssef Mohamed", email = "youssefmohamed@diracsystems.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
task1 = "task1:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
